trigger: none
pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: 'Build App'
  jobs:
  - job:
    steps:
      - bash: echo "Checkout Latest Code"
  - job: 
    steps:
      - bash: echo "Build Docker Images"

- stage: 'Testing'
  jobs:
  - job: B1
  - job: B2
