trigger: 
  tags:
    include:
      - regression

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: 'Testing'
  jobs:
  - job: SetUp
    steps:
      - bash: echo "============Set up dependencies============"
      - task: Gradle@2
        inputs:
          gradleWrapperFile: 'gradlew'
          workingDirectory: '/Gradle'
          tasks: 'katalonCopyDependencies'
          publishJUnitResults: false
          javaHomeOption: 'JDKVersion'
          sonarQubeRunAnalysis: false
     

